export enum OnboardingStep {
  REGISTERED = 'REGISTERED',
  KYC_INITIATED = 'KYC_INITIATED',
  KYC_FAILED = 'KYC_FAILED',
  KYC_SUCCESS = 'KYC_SUCCESS',
  ACCRED_INITIATED = 'ACCRED_INITIATED',
  ACCRED_FAILED = 'ACCRED_FAILED',
  ACCRED_SUCCESS = 'ACCRED_SUCCESS',
  BANK_LINKED = 'BANK_LINKED',
  COMPLETE = 'COMPLETE',
}

export enum CheckStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  KYC_INITIATED = 'KYC_INITIATED',
  KYC_POLL_ATTEMPTED = 'KYC_POLL_ATTEMPTED',
  KYC_COMPLETED = 'KYC_COMPLETED',
  ACCRED_INITIATED = 'ACCRED_INITIATED',
  ACCRED_POLL_ATTEMPTED = 'ACCRED_POLL_ATTEMPTED',
  ACCRED_COMPLETED = 'ACCRED_COMPLETED',
  BANK_LINK_INITIATED = 'BANK_LINK_INITIATED',
  BANK_LINK_COMPLETED = 'BANK_LINK_COMPLETED',
  INVESTMENT_INITIATED = 'INVESTMENT_INITIATED',
  INVESTMENT_COMPLETED = 'INVESTMENT_COMPLETED',
}

export enum AuditStatus {
  SUCCESS = 'SUCCESS',
  FAILURE = 'FAILURE',
  PENDING = 'PENDING',
}

export enum BankAccountStatus {
  ACTIVE = 'ACTIVE',
  UNLINKED = 'UNLINKED',
}

export enum InvestmentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AccountType {
  CHECKING = 'CHECKING',
  SAVINGS = 'SAVINGS',
}

// Lowercase — matches what third-party providers return
export enum ProviderStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PENDING = 'pending',
}
